"""NPZ-based AHN reader providing the filter_tile / interpolate interface."""

import numpy as np
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class FastGridInterpolator:
    """
    Fast nearest-cell interpolation on a regular grid.

    Parameters
    ----------
    grid_x : 1-D array, ascending
    grid_y : 1-D array, descending (top → bottom)
    values  : 2-D array of shape (Ny, Nx)
    """

    def __init__(self, grid_x, grid_y, values):
        step_x = grid_x[1] - grid_x[0]
        step_y = grid_y[0] - grid_y[1]  # positive since y is descending
        self.bin_x = grid_x - step_x / 2
        self.bin_y = grid_y + step_y / 2
        self.values = values

    def __call__(self, positions):
        """
        Parameters
        ----------
        positions : array of shape (N, 2)
            Columns are (x, y).

        Returns
        -------
        Array of shape (N,) with interpolated z values.
        """
        positions = np.asarray(positions)
        x_idx = np.digitize(positions[:, 0], self.bin_x) - 1
        y_idx = np.digitize(positions[:, 1], self.bin_y, right=True) - 1

        # Clamp to valid range
        x_idx = np.clip(x_idx, 0, self.values.shape[1] - 1)
        y_idx = np.clip(y_idx, 0, self.values.shape[0] - 1)

        return self.values[y_idx, x_idx]


class PolygonNPZReader:
    """
    AHN reader for NPZ files generated by UPSW_neo's AHN processing step.

    NPZ files are expected at ``<ahn_folder>/ahn_<tilecode>.npz`` and contain
    arrays ``x`` (ascending), ``y`` (descending), ``ground`` (Ny × Nx) and
    ``building`` (Ny × Nx).  The reader exposes a ``ground_surface`` key so
    it is compatible with BGTPoleFuser and BGTStreetFurnitureFuser.

    Parameters
    ----------
    ahn_folder : str or Path
        Folder containing the .npz files.
    caching : bool (default: True)
        Cache the last loaded tile to avoid repeated disk reads.
    """

    def __init__(self, ahn_folder, caching=True):
        self.ahn_folder = Path(ahn_folder)
        self.caching = caching
        self._cache = {}

    def filter_tile(self, tilecode):
        """
        Return a dict with keys ``x``, ``y``, ``ground_surface``,
        ``building_surface`` for the requested tile.
        """
        if self.caching and tilecode in self._cache:
            return self._cache[tilecode]

        npz_path = self.ahn_folder / f'ahn_{tilecode}.npz'
        if not npz_path.exists():
            raise FileNotFoundError(f'AHN file not found: {npz_path}')

        data = np.load(npz_path)
        tile = {
            'x': data['x'].astype(float),
            'y': data['y'].astype(float),
            'ground_surface': data['ground'].astype(float),
            'building_surface': data['building'].astype(float),
        }

        if self.caching:
            self._cache = {tilecode: tile}  # keep only the latest tile

        return tile

    def interpolate(self, tilecode, points, mask=None, surface='ground_surface'):
        """
        Interpolate AHN surface heights at the given points.

        Parameters
        ----------
        tilecode : str
        points : array of shape (N, 3)
            The points at which to interpolate.  If ``mask`` is None all
            points are used; otherwise ``points[mask]`` is used.
        mask : array of bool or None
            When provided, only ``points[mask]`` are interpolated.
        surface : str
            Key to look up in the tile dict (default: ``'ground_surface'``).

        Returns
        -------
        Array of shape (N_selected,) with interpolated z values.
        """
        tile = self.filter_tile(tilecode)
        fast_z = FastGridInterpolator(tile['x'], tile['y'], tile[surface])
        pts = points[mask] if mask is not None else points
        return fast_z(pts[:, :2])
